# traefik.prod.toml

# listen on port 80
[entryPoints]
    [entryPoints.web]
        address = ":80"
    [entryPoints.web.http]
        [entryPoints.web.http.redirections]
            [entryPoints.web.http.redirections.entryPoint]
                to = "websecure"
                scheme = "https"
    
    [entryPoints.websecure]
        address = ":443"

# Traefik dashboard over http
[api]
dashboard = true

[accessLog]

# containers are not discovered automatically
[providers]
    [providers.docker]
        exposedByDefault = false

#ssl certificates
[certificatesResolvers.letsencrypt.acme]
    email = "jd@thewb.co"
    storage = "/certificates/acme.json"
    [certificatesResolvers.letsencrypt.acme.httpChallenge]
        entryPoint = "web"